name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.1
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run tests
      run: make test
